[run]
init_cmds = [                      # Commands run in start
  ["make", "build"],
  ["./app"]
]
watch_all = true                   # Watch all sub-directories
watch_dirs = ["bin", "models", "services"]   # Directories to watch
watch_exts = [".go"]               # Extensions to watch
ignore = [".git", "vendor"]  # Directories to exclude from watching
ignore_files = []                  # Regexps for ignoring specific notifies
follow_symlinks = false            # Enable/disable following symbolic links of sub directories
build_delay = 400                 # Minimal interval to Trigger build event
interrupt_timout = 15              # Time to wait until force kill
graceful_kill = false              # Wait for exit and before directly kill
cmds = [                           # Commands to run
  ["make", "build"],
  ["./app"]
]

[sync]
listen_addr = ":5050"
remote_addr = ":5050"
