// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/anime.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Anime struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Anime) Reset()         { *m = Anime{} }
func (m *Anime) String() string { return proto.CompactTextString(m) }
func (*Anime) ProtoMessage()    {}
func (*Anime) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd224218081fca6f, []int{0}
}

func (m *Anime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anime.Unmarshal(m, b)
}
func (m *Anime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anime.Marshal(b, m, deterministic)
}
func (m *Anime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anime.Merge(m, src)
}
func (m *Anime) XXX_Size() int {
	return xxx_messageInfo_Anime.Size(m)
}
func (m *Anime) XXX_DiscardUnknown() {
	xxx_messageInfo_Anime.DiscardUnknown(m)
}

var xxx_messageInfo_Anime proto.InternalMessageInfo

func (m *Anime) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Anime) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Anime) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Anime) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type AnimeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeRequest) Reset()         { *m = AnimeRequest{} }
func (m *AnimeRequest) String() string { return proto.CompactTextString(m) }
func (*AnimeRequest) ProtoMessage()    {}
func (*AnimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd224218081fca6f, []int{1}
}

func (m *AnimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeRequest.Unmarshal(m, b)
}
func (m *AnimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeRequest.Marshal(b, m, deterministic)
}
func (m *AnimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeRequest.Merge(m, src)
}
func (m *AnimeRequest) XXX_Size() int {
	return xxx_messageInfo_AnimeRequest.Size(m)
}
func (m *AnimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeRequest proto.InternalMessageInfo

func (m *AnimeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AnimeResponse struct {
	Anime                *Anime   `protobuf:"bytes,1,opt,name=anime,proto3" json:"anime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeResponse) Reset()         { *m = AnimeResponse{} }
func (m *AnimeResponse) String() string { return proto.CompactTextString(m) }
func (*AnimeResponse) ProtoMessage()    {}
func (*AnimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd224218081fca6f, []int{2}
}

func (m *AnimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeResponse.Unmarshal(m, b)
}
func (m *AnimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeResponse.Marshal(b, m, deterministic)
}
func (m *AnimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeResponse.Merge(m, src)
}
func (m *AnimeResponse) XXX_Size() int {
	return xxx_messageInfo_AnimeResponse.Size(m)
}
func (m *AnimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeResponse proto.InternalMessageInfo

func (m *AnimeResponse) GetAnime() *Anime {
	if m != nil {
		return m.Anime
	}
	return nil
}

func init() {
	proto.RegisterType((*Anime)(nil), "proto.Anime")
	proto.RegisterType((*AnimeRequest)(nil), "proto.AnimeRequest")
	proto.RegisterType((*AnimeResponse)(nil), "proto.AnimeResponse")
}

func init() {
	proto.RegisterFile("proto/anime.proto", fileDescriptor_fd224218081fca6f)
}

var fileDescriptor_fd224218081fca6f = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x41, 0x0e, 0x82, 0x30,
	0x10, 0x45, 0x03, 0x58, 0x13, 0x46, 0x34, 0xb1, 0xb2, 0x20, 0x26, 0x1a, 0xd2, 0x15, 0x2b, 0x4c,
	0xe0, 0x04, 0x78, 0x04, 0x3c, 0x80, 0x41, 0x3a, 0x8b, 0x46, 0x05, 0x84, 0xc1, 0xf3, 0x1b, 0xda,
	0xb2, 0xc0, 0x55, 0xdb, 0xf7, 0x7e, 0xfa, 0x67, 0x60, 0xdf, 0xf5, 0x2d, 0xb5, 0x97, 0xaa, 0x51,
	0x6f, 0x4c, 0xf5, 0x9d, 0x33, 0x7d, 0x88, 0x27, 0xb0, 0x62, 0xa2, 0x7c, 0x07, 0xae, 0x92, 0x91,
	0x13, 0x3b, 0x89, 0x57, 0xba, 0x4a, 0xf2, 0x10, 0x18, 0x29, 0x7a, 0x61, 0xe4, 0xc6, 0x4e, 0xe2,
	0x97, 0xe6, 0xc1, 0x4f, 0x00, 0x75, 0x8f, 0x15, 0xa1, 0xbc, 0x57, 0x14, 0x79, 0x5a, 0xf9, 0x96,
	0x14, 0x34, 0xe9, 0xb1, 0x93, 0xb3, 0x5e, 0x19, 0x6d, 0x49, 0x41, 0xe2, 0x0c, 0x81, 0x2e, 0x2b,
	0xf1, 0x33, 0xe2, 0x40, 0xff, 0x9d, 0x22, 0x87, 0xad, 0xf5, 0x43, 0xd7, 0x36, 0x03, 0x72, 0x01,
	0x4c, 0xcf, 0xac, 0x33, 0x9b, 0x2c, 0x30, 0xb3, 0xa7, 0x26, 0x64, 0x54, 0x76, 0xb5, 0x9f, 0xde,
	0xb0, 0xff, 0xaa, 0x1a, 0x79, 0x36, 0x6f, 0x74, 0x58, 0xa4, 0x4d, 0xe5, 0x31, 0x5c, 0x42, 0xd3,
	0xf3, 0x58, 0x6b, 0x98, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x24, 0xf5, 0xff, 0x10, 0x28, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AnimeServiceClient is the client API for AnimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnimeServiceClient interface {
	Anime(ctx context.Context, in *AnimeRequest, opts ...grpc.CallOption) (*AnimeResponse, error)
}

type animeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnimeServiceClient(cc grpc.ClientConnInterface) AnimeServiceClient {
	return &animeServiceClient{cc}
}

func (c *animeServiceClient) Anime(ctx context.Context, in *AnimeRequest, opts ...grpc.CallOption) (*AnimeResponse, error) {
	out := new(AnimeResponse)
	err := c.cc.Invoke(ctx, "/proto.AnimeService/Anime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimeServiceServer is the server API for AnimeService service.
type AnimeServiceServer interface {
	Anime(context.Context, *AnimeRequest) (*AnimeResponse, error)
}

// UnimplementedAnimeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAnimeServiceServer struct {
}

func (*UnimplementedAnimeServiceServer) Anime(ctx context.Context, req *AnimeRequest) (*AnimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Anime not implemented")
}

func RegisterAnimeServiceServer(s *grpc.Server, srv AnimeServiceServer) {
	s.RegisterService(&_AnimeService_serviceDesc, srv)
}

func _AnimeService_Anime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeServiceServer).Anime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AnimeService/Anime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeServiceServer).Anime(ctx, req.(*AnimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AnimeService",
	HandlerType: (*AnimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Anime",
			Handler:    _AnimeService_Anime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/anime.proto",
}
