// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/anime.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnimeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeRequest) Reset()         { *m = AnimeRequest{} }
func (m *AnimeRequest) String() string { return proto.CompactTextString(m) }
func (*AnimeRequest) ProtoMessage()    {}
func (*AnimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd224218081fca6f, []int{0}
}

func (m *AnimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeRequest.Unmarshal(m, b)
}
func (m *AnimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeRequest.Marshal(b, m, deterministic)
}
func (m *AnimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeRequest.Merge(m, src)
}
func (m *AnimeRequest) XXX_Size() int {
	return xxx_messageInfo_AnimeRequest.Size(m)
}
func (m *AnimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeRequest proto.InternalMessageInfo

func (m *AnimeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AnimeReply struct {
	Anime                *Anime   `protobuf:"bytes,1,opt,name=anime,proto3" json:"anime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeReply) Reset()         { *m = AnimeReply{} }
func (m *AnimeReply) String() string { return proto.CompactTextString(m) }
func (*AnimeReply) ProtoMessage()    {}
func (*AnimeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd224218081fca6f, []int{1}
}

func (m *AnimeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeReply.Unmarshal(m, b)
}
func (m *AnimeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeReply.Marshal(b, m, deterministic)
}
func (m *AnimeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeReply.Merge(m, src)
}
func (m *AnimeReply) XXX_Size() int {
	return xxx_messageInfo_AnimeReply.Size(m)
}
func (m *AnimeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeReply.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeReply proto.InternalMessageInfo

func (m *AnimeReply) GetAnime() *Anime {
	if m != nil {
		return m.Anime
	}
	return nil
}

type Anime struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Anime) Reset()         { *m = Anime{} }
func (m *Anime) String() string { return proto.CompactTextString(m) }
func (*Anime) ProtoMessage()    {}
func (*Anime) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd224218081fca6f, []int{2}
}

func (m *Anime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Anime.Unmarshal(m, b)
}
func (m *Anime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Anime.Marshal(b, m, deterministic)
}
func (m *Anime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Anime.Merge(m, src)
}
func (m *Anime) XXX_Size() int {
	return xxx_messageInfo_Anime.Size(m)
}
func (m *Anime) XXX_DiscardUnknown() {
	xxx_messageInfo_Anime.DiscardUnknown(m)
}

var xxx_messageInfo_Anime proto.InternalMessageInfo

func (m *Anime) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Anime) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Anime) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Anime) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*AnimeRequest)(nil), "proto.AnimeRequest")
	proto.RegisterType((*AnimeReply)(nil), "proto.AnimeReply")
	proto.RegisterType((*Anime)(nil), "proto.Anime")
}

func init() {
	proto.RegisterFile("proto/anime.proto", fileDescriptor_fd224218081fca6f)
}

var fileDescriptor_fd224218081fca6f = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcc, 0xcb, 0xcc, 0x4d, 0xd5, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x94, 0x92, 0x1c,
	0x17, 0x8f, 0x23, 0x48, 0x34, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x88, 0x8f, 0x8b, 0x29,
	0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x88, 0x29, 0x33, 0x45, 0xc9, 0x80, 0x8b, 0x0b,
	0x2a, 0x5f, 0x90, 0x53, 0x29, 0xa4, 0xc4, 0xc5, 0x0a, 0x36, 0x03, 0xac, 0x80, 0xdb, 0x88, 0x07,
	0x62, 0x96, 0x1e, 0x44, 0x05, 0x44, 0x4a, 0x29, 0x9b, 0x8b, 0x15, 0xcc, 0x47, 0x37, 0x4a, 0x48,
	0x84, 0x8b, 0xb5, 0x24, 0xb3, 0x24, 0x27, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2,
	0x11, 0x92, 0xe5, 0xe2, 0x4a, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x4d, 0x89, 0x4f, 0x2c, 0x91, 0x60,
	0x06, 0x4b, 0x71, 0x42, 0x45, 0x1c, 0x4b, 0x40, 0xd2, 0xa5, 0x05, 0x29, 0x30, 0x69, 0x16, 0x88,
	0x34, 0x54, 0xc4, 0xb1, 0xc4, 0xc8, 0x1e, 0xea, 0xfc, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54,
	0x21, 0x7d, 0x98, 0xe5, 0xc2, 0x28, 0x4e, 0x83, 0x78, 0x4e, 0x4a, 0x10, 0x55, 0xb0, 0x20, 0xa7,
	0x32, 0x89, 0x0d, 0x2c, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xc6, 0x83, 0x06, 0x22,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AnimeServiceClient is the client API for AnimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnimeServiceClient interface {
	Anime(ctx context.Context, in *AnimeRequest, opts ...grpc.CallOption) (*AnimeReply, error)
}

type animeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnimeServiceClient(cc grpc.ClientConnInterface) AnimeServiceClient {
	return &animeServiceClient{cc}
}

func (c *animeServiceClient) Anime(ctx context.Context, in *AnimeRequest, opts ...grpc.CallOption) (*AnimeReply, error) {
	out := new(AnimeReply)
	err := c.cc.Invoke(ctx, "/proto.AnimeService/Anime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimeServiceServer is the server API for AnimeService service.
type AnimeServiceServer interface {
	Anime(context.Context, *AnimeRequest) (*AnimeReply, error)
}

// UnimplementedAnimeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAnimeServiceServer struct {
}

func (*UnimplementedAnimeServiceServer) Anime(ctx context.Context, req *AnimeRequest) (*AnimeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Anime not implemented")
}

func RegisterAnimeServiceServer(s *grpc.Server, srv AnimeServiceServer) {
	s.RegisterService(&_AnimeService_serviceDesc, srv)
}

func _AnimeService_Anime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeServiceServer).Anime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AnimeService/Anime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeServiceServer).Anime(ctx, req.(*AnimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AnimeService",
	HandlerType: (*AnimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Anime",
			Handler:    _AnimeService_Anime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/anime.proto",
}
