// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Join_JoinType int32

const (
	Join_INNER_JOIN Join_JoinType = 0
	Join_LEFT_JOIN  Join_JoinType = 1
	Join_RIGHT_JOIN Join_JoinType = 2
)

var Join_JoinType_name = map[int32]string{
	0: "INNER_JOIN",
	1: "LEFT_JOIN",
	2: "RIGHT_JOIN",
}

var Join_JoinType_value = map[string]int32{
	"INNER_JOIN": 0,
	"LEFT_JOIN":  1,
	"RIGHT_JOIN": 2,
}

func (x Join_JoinType) String() string {
	return proto.EnumName(Join_JoinType_name, int32(x))
}

func (Join_JoinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{4, 0}
}

// OrderBy field name
type OrderBy struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Descending           bool     `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBy) Reset()         { *m = OrderBy{} }
func (m *OrderBy) String() string { return proto.CompactTextString(m) }
func (*OrderBy) ProtoMessage()    {}
func (*OrderBy) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{0}
}

func (m *OrderBy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBy.Unmarshal(m, b)
}
func (m *OrderBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBy.Marshal(b, m, deterministic)
}
func (m *OrderBy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBy.Merge(m, src)
}
func (m *OrderBy) XXX_Size() int {
	return xxx_messageInfo_OrderBy.Size(m)
}
func (m *OrderBy) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBy.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBy proto.InternalMessageInfo

func (m *OrderBy) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *OrderBy) GetDescending() bool {
	if m != nil {
		return m.Descending
	}
	return false
}

// GroupBy field name
type GroupBy struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupBy) Reset()         { *m = GroupBy{} }
func (m *GroupBy) String() string { return proto.CompactTextString(m) }
func (*GroupBy) ProtoMessage()    {}
func (*GroupBy) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{1}
}

func (m *GroupBy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupBy.Unmarshal(m, b)
}
func (m *GroupBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupBy.Marshal(b, m, deterministic)
}
func (m *GroupBy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupBy.Merge(m, src)
}
func (m *GroupBy) XXX_Size() int {
	return xxx_messageInfo_GroupBy.Size(m)
}
func (m *GroupBy) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupBy.DiscardUnknown(m)
}

var xxx_messageInfo_GroupBy proto.InternalMessageInfo

func (m *GroupBy) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

// Less than the value specified in the specified field
type LessThan struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LessThan) Reset()         { *m = LessThan{} }
func (m *LessThan) String() string { return proto.CompactTextString(m) }
func (*LessThan) ProtoMessage()    {}
func (*LessThan) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{2}
}

func (m *LessThan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LessThan.Unmarshal(m, b)
}
func (m *LessThan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LessThan.Marshal(b, m, deterministic)
}
func (m *LessThan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LessThan.Merge(m, src)
}
func (m *LessThan) XXX_Size() int {
	return xxx_messageInfo_LessThan.Size(m)
}
func (m *LessThan) XXX_DiscardUnknown() {
	xxx_messageInfo_LessThan.DiscardUnknown(m)
}

var xxx_messageInfo_LessThan proto.InternalMessageInfo

func (m *LessThan) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *LessThan) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Greater than the value specified in the specified field
type GreaterThan struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreaterThan) Reset()         { *m = GreaterThan{} }
func (m *GreaterThan) String() string { return proto.CompactTextString(m) }
func (*GreaterThan) ProtoMessage()    {}
func (*GreaterThan) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{3}
}

func (m *GreaterThan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreaterThan.Unmarshal(m, b)
}
func (m *GreaterThan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreaterThan.Marshal(b, m, deterministic)
}
func (m *GreaterThan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreaterThan.Merge(m, src)
}
func (m *GreaterThan) XXX_Size() int {
	return xxx_messageInfo_GreaterThan.Size(m)
}
func (m *GreaterThan) XXX_DiscardUnknown() {
	xxx_messageInfo_GreaterThan.DiscardUnknown(m)
}

var xxx_messageInfo_GreaterThan proto.InternalMessageInfo

func (m *GreaterThan) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *GreaterThan) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Join struct {
	JoinType             Join_JoinType `protobuf:"varint,1,opt,name=join_type,json=joinType,proto3,enum=proto.Join_JoinType" json:"join_type,omitempty"`
	Field                string        `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Join) Reset()         { *m = Join{} }
func (m *Join) String() string { return proto.CompactTextString(m) }
func (*Join) ProtoMessage()    {}
func (*Join) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{4}
}

func (m *Join) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Join.Unmarshal(m, b)
}
func (m *Join) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Join.Marshal(b, m, deterministic)
}
func (m *Join) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Join.Merge(m, src)
}
func (m *Join) XXX_Size() int {
	return xxx_messageInfo_Join.Size(m)
}
func (m *Join) XXX_DiscardUnknown() {
	xxx_messageInfo_Join.DiscardUnknown(m)
}

var xxx_messageInfo_Join proto.InternalMessageInfo

func (m *Join) GetJoinType() Join_JoinType {
	if m != nil {
		return m.JoinType
	}
	return Join_INNER_JOIN
}

func (m *Join) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type PaginationRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationRequest) Reset()         { *m = PaginationRequest{} }
func (m *PaginationRequest) String() string { return proto.CompactTextString(m) }
func (*PaginationRequest) ProtoMessage()    {}
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{5}
}

func (m *PaginationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationRequest.Unmarshal(m, b)
}
func (m *PaginationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationRequest.Marshal(b, m, deterministic)
}
func (m *PaginationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationRequest.Merge(m, src)
}
func (m *PaginationRequest) XXX_Size() int {
	return xxx_messageInfo_PaginationRequest.Size(m)
}
func (m *PaginationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationRequest proto.InternalMessageInfo

func (m *PaginationRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PaginationRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.Join_JoinType", Join_JoinType_name, Join_JoinType_value)
	proto.RegisterType((*OrderBy)(nil), "proto.OrderBy")
	proto.RegisterType((*GroupBy)(nil), "proto.GroupBy")
	proto.RegisterType((*LessThan)(nil), "proto.LessThan")
	proto.RegisterType((*GreaterThan)(nil), "proto.GreaterThan")
	proto.RegisterType((*Join)(nil), "proto.Join")
	proto.RegisterType((*PaginationRequest)(nil), "proto.PaginationRequest")
}

func init() { proto.RegisterFile("proto/common.proto", fileDescriptor_1747d3070a2311a0) }

var fileDescriptor_1747d3070a2311a0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8f, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x6d, 0x67, 0xb7, 0xf6, 0x15, 0x87, 0x86, 0x22, 0x3b, 0xe9, 0xe8, 0x69, 0xa7, 0x89,
	0x0a, 0xc2, 0x4e, 0xa2, 0x30, 0x6b, 0xc7, 0xe8, 0x24, 0xf4, 0x3e, 0xea, 0xfa, 0x76, 0x66, 0xb4,
	0x49, 0x4d, 0x53, 0xa1, 0x5f, 0xc1, 0x4f, 0x2d, 0x4d, 0x3b, 0xdc, 0x65, 0x07, 0x2f, 0x49, 0x7e,
	0x79, 0xff, 0x3c, 0xcf, 0x03, 0xa4, 0x90, 0x42, 0x89, 0xdb, 0x8d, 0xc8, 0x73, 0xc1, 0xa7, 0x1a,
	0x88, 0xa5, 0x2f, 0xef, 0x09, 0x06, 0x2b, 0x99, 0xa0, 0x7c, 0xa9, 0x89, 0x0b, 0x56, 0xca, 0x30,
	0x4b, 0x46, 0xc6, 0xd8, 0x98, 0x38, 0xb4, 0x05, 0x72, 0x0d, 0x90, 0x60, 0xb9, 0x41, 0x9e, 0x30,
	0xbe, 0x1d, 0x99, 0x63, 0x63, 0x62, 0xd3, 0x83, 0x1f, 0xef, 0x06, 0x06, 0xbe, 0x14, 0x55, 0x71,
	0x6c, 0x81, 0xf7, 0x08, 0xf6, 0x12, 0xcb, 0x32, 0xfa, 0x8c, 0xf9, 0x11, 0x09, 0x17, 0xac, 0xef,
	0x38, 0xab, 0x50, 0x6f, 0xef, 0xd1, 0x16, 0xbc, 0x19, 0x9c, 0xf9, 0x12, 0x63, 0x85, 0xf2, 0xdf,
	0xa3, 0x3f, 0x06, 0x9c, 0x2e, 0x04, 0xe3, 0xe4, 0x0e, 0x9c, 0x9d, 0x60, 0x7c, 0xad, 0xea, 0x02,
	0xf5, 0xe0, 0xf0, 0xde, 0x6d, 0xf3, 0x4f, 0x9b, 0xba, 0x3e, 0xa2, 0xba, 0x40, 0x6a, 0xef, 0xba,
	0xd7, 0x9f, 0x8e, 0x79, 0x18, 0x62, 0x06, 0xf6, 0xbe, 0x97, 0x0c, 0x01, 0x82, 0x30, 0x9c, 0xd3,
	0xf5, 0x62, 0x15, 0x84, 0x17, 0x27, 0xe4, 0x1c, 0x9c, 0xe5, 0xfc, 0x35, 0x6a, 0xd1, 0x68, 0xca,
	0x34, 0xf0, 0xdf, 0x3a, 0x36, 0xbd, 0x67, 0xb8, 0x7c, 0x8f, 0xb7, 0x8c, 0xc7, 0x8a, 0x09, 0x4e,
	0xf1, 0xab, 0xc2, 0x52, 0x91, 0x2b, 0xe8, 0x8b, 0x34, 0x2d, 0x51, 0x69, 0x57, 0x3d, 0xda, 0x51,
	0xa3, 0x9e, 0xb1, 0x9c, 0xa9, 0x7d, 0x1e, 0x0d, 0x1f, 0x7d, 0x6d, 0xf9, 0xe1, 0x37, 0x00, 0x00,
	0xff, 0xff, 0xed, 0x57, 0x7f, 0x47, 0xc8, 0x01, 0x00, 0x00,
}
