// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/episode.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Episode struct {
	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Thumbnail    string `protobuf:"bytes,2,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	EpisodeOrder int64  `protobuf:"varint,3,opt,name=episode_order,json=episodeOrder,proto3" json:"episode_order,omitempty"`
	EpisodeCode  string `protobuf:"bytes,4,opt,name=episode_code,json=episodeCode,proto3" json:"episode_code,omitempty"`
	CreatedAt    string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Relations
	ReleaseId            int64    `protobuf:"varint,7,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Episode) Reset()         { *m = Episode{} }
func (m *Episode) String() string { return proto.CompactTextString(m) }
func (*Episode) ProtoMessage()    {}
func (*Episode) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{0}
}

func (m *Episode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Episode.Unmarshal(m, b)
}
func (m *Episode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Episode.Marshal(b, m, deterministic)
}
func (m *Episode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Episode.Merge(m, src)
}
func (m *Episode) XXX_Size() int {
	return xxx_messageInfo_Episode.Size(m)
}
func (m *Episode) XXX_DiscardUnknown() {
	xxx_messageInfo_Episode.DiscardUnknown(m)
}

var xxx_messageInfo_Episode proto.InternalMessageInfo

func (m *Episode) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Episode) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Episode) GetEpisodeOrder() int64 {
	if m != nil {
		return m.EpisodeOrder
	}
	return 0
}

func (m *Episode) GetEpisodeCode() string {
	if m != nil {
		return m.EpisodeCode
	}
	return ""
}

func (m *Episode) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Episode) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Episode) GetReleaseId() int64 {
	if m != nil {
		return m.ReleaseId
	}
	return 0
}

type EpisodeQuery struct {
	ReleaseId int64 `protobuf:"varint,3,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	// Pagination
	Offset               int64    `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpisodeQuery) Reset()         { *m = EpisodeQuery{} }
func (m *EpisodeQuery) String() string { return proto.CompactTextString(m) }
func (*EpisodeQuery) ProtoMessage()    {}
func (*EpisodeQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{1}
}

func (m *EpisodeQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodeQuery.Unmarshal(m, b)
}
func (m *EpisodeQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodeQuery.Marshal(b, m, deterministic)
}
func (m *EpisodeQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodeQuery.Merge(m, src)
}
func (m *EpisodeQuery) XXX_Size() int {
	return xxx_messageInfo_EpisodeQuery.Size(m)
}
func (m *EpisodeQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodeQuery.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodeQuery proto.InternalMessageInfo

func (m *EpisodeQuery) GetReleaseId() int64 {
	if m != nil {
		return m.ReleaseId
	}
	return 0
}

func (m *EpisodeQuery) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *EpisodeQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type EpisodeRequest struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReleaseId            int64        `protobuf:"varint,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	OrderBy              *OrderBy     `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	LessThan             *LessThan    `protobuf:"bytes,4,opt,name=lessThan,proto3" json:"lessThan,omitempty"`
	GreaterThan          *GreaterThan `protobuf:"bytes,5,opt,name=greaterThan,proto3" json:"greaterThan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EpisodeRequest) Reset()         { *m = EpisodeRequest{} }
func (m *EpisodeRequest) String() string { return proto.CompactTextString(m) }
func (*EpisodeRequest) ProtoMessage()    {}
func (*EpisodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{2}
}

func (m *EpisodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodeRequest.Unmarshal(m, b)
}
func (m *EpisodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodeRequest.Marshal(b, m, deterministic)
}
func (m *EpisodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodeRequest.Merge(m, src)
}
func (m *EpisodeRequest) XXX_Size() int {
	return xxx_messageInfo_EpisodeRequest.Size(m)
}
func (m *EpisodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodeRequest proto.InternalMessageInfo

func (m *EpisodeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EpisodeRequest) GetReleaseId() int64 {
	if m != nil {
		return m.ReleaseId
	}
	return 0
}

func (m *EpisodeRequest) GetOrderBy() *OrderBy {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *EpisodeRequest) GetLessThan() *LessThan {
	if m != nil {
		return m.LessThan
	}
	return nil
}

func (m *EpisodeRequest) GetGreaterThan() *GreaterThan {
	if m != nil {
		return m.GreaterThan
	}
	return nil
}

type LatestEpisodeRequest struct {
	ReleaseId            int64    `protobuf:"varint,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatestEpisodeRequest) Reset()         { *m = LatestEpisodeRequest{} }
func (m *LatestEpisodeRequest) String() string { return proto.CompactTextString(m) }
func (*LatestEpisodeRequest) ProtoMessage()    {}
func (*LatestEpisodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{3}
}

func (m *LatestEpisodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestEpisodeRequest.Unmarshal(m, b)
}
func (m *LatestEpisodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestEpisodeRequest.Marshal(b, m, deterministic)
}
func (m *LatestEpisodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestEpisodeRequest.Merge(m, src)
}
func (m *LatestEpisodeRequest) XXX_Size() int {
	return xxx_messageInfo_LatestEpisodeRequest.Size(m)
}
func (m *LatestEpisodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestEpisodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LatestEpisodeRequest proto.InternalMessageInfo

func (m *LatestEpisodeRequest) GetReleaseId() int64 {
	if m != nil {
		return m.ReleaseId
	}
	return 0
}

type EpisodeCountRequest struct {
	ReleaseId            int64    `protobuf:"varint,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpisodeCountRequest) Reset()         { *m = EpisodeCountRequest{} }
func (m *EpisodeCountRequest) String() string { return proto.CompactTextString(m) }
func (*EpisodeCountRequest) ProtoMessage()    {}
func (*EpisodeCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{4}
}

func (m *EpisodeCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodeCountRequest.Unmarshal(m, b)
}
func (m *EpisodeCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodeCountRequest.Marshal(b, m, deterministic)
}
func (m *EpisodeCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodeCountRequest.Merge(m, src)
}
func (m *EpisodeCountRequest) XXX_Size() int {
	return xxx_messageInfo_EpisodeCountRequest.Size(m)
}
func (m *EpisodeCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodeCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodeCountRequest proto.InternalMessageInfo

func (m *EpisodeCountRequest) GetReleaseId() int64 {
	if m != nil {
		return m.ReleaseId
	}
	return 0
}

type EpisodesRequest struct {
	Query                *EpisodeQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	OrderBy              *OrderBy      `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EpisodesRequest) Reset()         { *m = EpisodesRequest{} }
func (m *EpisodesRequest) String() string { return proto.CompactTextString(m) }
func (*EpisodesRequest) ProtoMessage()    {}
func (*EpisodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{5}
}

func (m *EpisodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodesRequest.Unmarshal(m, b)
}
func (m *EpisodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodesRequest.Marshal(b, m, deterministic)
}
func (m *EpisodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodesRequest.Merge(m, src)
}
func (m *EpisodesRequest) XXX_Size() int {
	return xxx_messageInfo_EpisodesRequest.Size(m)
}
func (m *EpisodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodesRequest proto.InternalMessageInfo

func (m *EpisodesRequest) GetQuery() *EpisodeQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *EpisodesRequest) GetOrderBy() *OrderBy {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

type EpisodeResponse struct {
	Episode              *Episode `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpisodeResponse) Reset()         { *m = EpisodeResponse{} }
func (m *EpisodeResponse) String() string { return proto.CompactTextString(m) }
func (*EpisodeResponse) ProtoMessage()    {}
func (*EpisodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{6}
}

func (m *EpisodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodeResponse.Unmarshal(m, b)
}
func (m *EpisodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodeResponse.Marshal(b, m, deterministic)
}
func (m *EpisodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodeResponse.Merge(m, src)
}
func (m *EpisodeResponse) XXX_Size() int {
	return xxx_messageInfo_EpisodeResponse.Size(m)
}
func (m *EpisodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodeResponse proto.InternalMessageInfo

func (m *EpisodeResponse) GetEpisode() *Episode {
	if m != nil {
		return m.Episode
	}
	return nil
}

type EpisodeCountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpisodeCountResponse) Reset()         { *m = EpisodeCountResponse{} }
func (m *EpisodeCountResponse) String() string { return proto.CompactTextString(m) }
func (*EpisodeCountResponse) ProtoMessage()    {}
func (*EpisodeCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{7}
}

func (m *EpisodeCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodeCountResponse.Unmarshal(m, b)
}
func (m *EpisodeCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodeCountResponse.Marshal(b, m, deterministic)
}
func (m *EpisodeCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodeCountResponse.Merge(m, src)
}
func (m *EpisodeCountResponse) XXX_Size() int {
	return xxx_messageInfo_EpisodeCountResponse.Size(m)
}
func (m *EpisodeCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodeCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodeCountResponse proto.InternalMessageInfo

func (m *EpisodeCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type EpisodesResponse struct {
	Episodes             []*Episode `protobuf:"bytes,1,rep,name=episodes,proto3" json:"episodes,omitempty"`
	Count                uint64     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EpisodesResponse) Reset()         { *m = EpisodesResponse{} }
func (m *EpisodesResponse) String() string { return proto.CompactTextString(m) }
func (*EpisodesResponse) ProtoMessage()    {}
func (*EpisodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{8}
}

func (m *EpisodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodesResponse.Unmarshal(m, b)
}
func (m *EpisodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodesResponse.Marshal(b, m, deterministic)
}
func (m *EpisodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodesResponse.Merge(m, src)
}
func (m *EpisodesResponse) XXX_Size() int {
	return xxx_messageInfo_EpisodesResponse.Size(m)
}
func (m *EpisodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodesResponse proto.InternalMessageInfo

func (m *EpisodesResponse) GetEpisodes() []*Episode {
	if m != nil {
		return m.Episodes
	}
	return nil
}

func (m *EpisodesResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type EpisodeSubtitle struct {
	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SubtitleCode string `protobuf:"bytes,2,opt,name=subtitle_code,json=subtitleCode,proto3" json:"subtitle_code,omitempty"`
	// Relations
	EpisodeId            int64    `protobuf:"varint,7,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	LanguageId           int64    `protobuf:"varint,8,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpisodeSubtitle) Reset()         { *m = EpisodeSubtitle{} }
func (m *EpisodeSubtitle) String() string { return proto.CompactTextString(m) }
func (*EpisodeSubtitle) ProtoMessage()    {}
func (*EpisodeSubtitle) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{9}
}

func (m *EpisodeSubtitle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodeSubtitle.Unmarshal(m, b)
}
func (m *EpisodeSubtitle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodeSubtitle.Marshal(b, m, deterministic)
}
func (m *EpisodeSubtitle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodeSubtitle.Merge(m, src)
}
func (m *EpisodeSubtitle) XXX_Size() int {
	return xxx_messageInfo_EpisodeSubtitle.Size(m)
}
func (m *EpisodeSubtitle) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodeSubtitle.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodeSubtitle proto.InternalMessageInfo

func (m *EpisodeSubtitle) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EpisodeSubtitle) GetSubtitleCode() string {
	if m != nil {
		return m.SubtitleCode
	}
	return ""
}

func (m *EpisodeSubtitle) GetEpisodeId() int64 {
	if m != nil {
		return m.EpisodeId
	}
	return 0
}

func (m *EpisodeSubtitle) GetLanguageId() int64 {
	if m != nil {
		return m.LanguageId
	}
	return 0
}

type EpisodeSubtitlesRequest struct {
	EpisodeId            int64    `protobuf:"varint,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpisodeSubtitlesRequest) Reset()         { *m = EpisodeSubtitlesRequest{} }
func (m *EpisodeSubtitlesRequest) String() string { return proto.CompactTextString(m) }
func (*EpisodeSubtitlesRequest) ProtoMessage()    {}
func (*EpisodeSubtitlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{10}
}

func (m *EpisodeSubtitlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodeSubtitlesRequest.Unmarshal(m, b)
}
func (m *EpisodeSubtitlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodeSubtitlesRequest.Marshal(b, m, deterministic)
}
func (m *EpisodeSubtitlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodeSubtitlesRequest.Merge(m, src)
}
func (m *EpisodeSubtitlesRequest) XXX_Size() int {
	return xxx_messageInfo_EpisodeSubtitlesRequest.Size(m)
}
func (m *EpisodeSubtitlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodeSubtitlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodeSubtitlesRequest proto.InternalMessageInfo

func (m *EpisodeSubtitlesRequest) GetEpisodeId() int64 {
	if m != nil {
		return m.EpisodeId
	}
	return 0
}

type EpisodeSubtitlesListResponse struct {
	EpisodeSubtitles     []*EpisodeSubtitle `protobuf:"bytes,1,rep,name=EpisodeSubtitles,proto3" json:"EpisodeSubtitles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EpisodeSubtitlesListResponse) Reset()         { *m = EpisodeSubtitlesListResponse{} }
func (m *EpisodeSubtitlesListResponse) String() string { return proto.CompactTextString(m) }
func (*EpisodeSubtitlesListResponse) ProtoMessage()    {}
func (*EpisodeSubtitlesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{11}
}

func (m *EpisodeSubtitlesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodeSubtitlesListResponse.Unmarshal(m, b)
}
func (m *EpisodeSubtitlesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodeSubtitlesListResponse.Marshal(b, m, deterministic)
}
func (m *EpisodeSubtitlesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodeSubtitlesListResponse.Merge(m, src)
}
func (m *EpisodeSubtitlesListResponse) XXX_Size() int {
	return xxx_messageInfo_EpisodeSubtitlesListResponse.Size(m)
}
func (m *EpisodeSubtitlesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodeSubtitlesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodeSubtitlesListResponse proto.InternalMessageInfo

func (m *EpisodeSubtitlesListResponse) GetEpisodeSubtitles() []*EpisodeSubtitle {
	if m != nil {
		return m.EpisodeSubtitles
	}
	return nil
}

type EpisodeSeen struct {
	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Relations
	EpisodeId            int64    `protobuf:"varint,7,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpisodeSeen) Reset()         { *m = EpisodeSeen{} }
func (m *EpisodeSeen) String() string { return proto.CompactTextString(m) }
func (*EpisodeSeen) ProtoMessage()    {}
func (*EpisodeSeen) Descriptor() ([]byte, []int) {
	return fileDescriptor_536a535dba699a81, []int{12}
}

func (m *EpisodeSeen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodeSeen.Unmarshal(m, b)
}
func (m *EpisodeSeen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodeSeen.Marshal(b, m, deterministic)
}
func (m *EpisodeSeen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodeSeen.Merge(m, src)
}
func (m *EpisodeSeen) XXX_Size() int {
	return xxx_messageInfo_EpisodeSeen.Size(m)
}
func (m *EpisodeSeen) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodeSeen.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodeSeen proto.InternalMessageInfo

func (m *EpisodeSeen) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EpisodeSeen) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *EpisodeSeen) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *EpisodeSeen) GetEpisodeId() int64 {
	if m != nil {
		return m.EpisodeId
	}
	return 0
}

func init() {
	proto.RegisterType((*Episode)(nil), "proto.Episode")
	proto.RegisterType((*EpisodeQuery)(nil), "proto.EpisodeQuery")
	proto.RegisterType((*EpisodeRequest)(nil), "proto.EpisodeRequest")
	proto.RegisterType((*LatestEpisodeRequest)(nil), "proto.LatestEpisodeRequest")
	proto.RegisterType((*EpisodeCountRequest)(nil), "proto.EpisodeCountRequest")
	proto.RegisterType((*EpisodesRequest)(nil), "proto.EpisodesRequest")
	proto.RegisterType((*EpisodeResponse)(nil), "proto.EpisodeResponse")
	proto.RegisterType((*EpisodeCountResponse)(nil), "proto.EpisodeCountResponse")
	proto.RegisterType((*EpisodesResponse)(nil), "proto.EpisodesResponse")
	proto.RegisterType((*EpisodeSubtitle)(nil), "proto.EpisodeSubtitle")
	proto.RegisterType((*EpisodeSubtitlesRequest)(nil), "proto.EpisodeSubtitlesRequest")
	proto.RegisterType((*EpisodeSubtitlesListResponse)(nil), "proto.EpisodeSubtitlesListResponse")
	proto.RegisterType((*EpisodeSeen)(nil), "proto.EpisodeSeen")
}

func init() { proto.RegisterFile("proto/episode.proto", fileDescriptor_536a535dba699a81) }

var fileDescriptor_536a535dba699a81 = []byte{
	// 674 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x95, 0xe3, 0xba, 0x49, 0xc7, 0x6d, 0xfa, 0x69, 0x9b, 0xaf, 0xb5, 0xd2, 0x02, 0xc5, 0xbd,
	0x69, 0x01, 0x15, 0x29, 0x14, 0xa9, 0x52, 0xaf, 0x5a, 0xa8, 0x4a, 0xa4, 0x08, 0x84, 0x5b, 0x89,
	0x0b, 0x2e, 0x22, 0x27, 0xde, 0xa6, 0x96, 0x1c, 0x3b, 0xf5, 0xae, 0x41, 0xe1, 0x01, 0x78, 0x3b,
	0xde, 0x80, 0xe7, 0xe0, 0x1a, 0x79, 0x77, 0xd6, 0x7f, 0x71, 0x23, 0x04, 0x57, 0xc9, 0x9e, 0x73,
	0x76, 0xc6, 0x73, 0x66, 0x67, 0x60, 0x6b, 0x16, 0x47, 0x3c, 0x7a, 0x49, 0x67, 0x3e, 0x8b, 0x3c,
	0x7a, 0x2c, 0x4e, 0xc4, 0x10, 0x3f, 0x5d, 0x22, 0xb9, 0x71, 0x34, 0x9d, 0x46, 0xa1, 0xa4, 0xec,
	0x9f, 0x1a, 0x34, 0x2f, 0xa5, 0x98, 0xb4, 0xa1, 0xe1, 0x7b, 0x96, 0xb6, 0xaf, 0x1d, 0xea, 0x4e,
	0xc3, 0xf7, 0xc8, 0x1e, 0xac, 0xf1, 0xbb, 0x64, 0x3a, 0x0a, 0x5d, 0x3f, 0xb0, 0x1a, 0xfb, 0xda,
	0xe1, 0x9a, 0x93, 0x03, 0xe4, 0x00, 0x36, 0x30, 0xcb, 0x30, 0x8a, 0x3d, 0x1a, 0x5b, 0xba, 0xb8,
	0xb8, 0x8e, 0xe0, 0x87, 0x14, 0x23, 0x4f, 0x41, 0x9d, 0x87, 0xe3, 0xc8, 0xa3, 0xd6, 0x8a, 0x88,
	0x62, 0x22, 0xf6, 0x26, 0xcd, 0xfa, 0x08, 0x60, 0x1c, 0x53, 0x97, 0x53, 0x6f, 0xe8, 0x72, 0xcb,
	0x90, 0x69, 0x10, 0x39, 0xe7, 0x29, 0x9d, 0xcc, 0x3c, 0x45, 0xaf, 0x4a, 0x1a, 0x11, 0x49, 0xc7,
	0x34, 0xa0, 0x2e, 0xa3, 0x43, 0xdf, 0xb3, 0x9a, 0xe2, 0x13, 0xd6, 0x10, 0xe9, 0x7b, 0xf6, 0x67,
	0x58, 0xc7, 0xea, 0x3e, 0x26, 0x34, 0x9e, 0x57, 0xe4, 0x7a, 0x45, 0x4e, 0xb6, 0x61, 0x35, 0xba,
	0xbd, 0x65, 0x94, 0x5b, 0x20, 0x28, 0x3c, 0x91, 0x0e, 0x18, 0x81, 0x3f, 0xf5, 0xb9, 0x65, 0x0a,
	0x58, 0x1e, 0xec, 0x1f, 0x1a, 0xb4, 0x31, 0xba, 0x43, 0xef, 0x13, 0xca, 0xf8, 0x82, 0x85, 0xe5,
	0x7c, 0x8d, 0x6a, 0xbe, 0x23, 0x68, 0x09, 0xef, 0x86, 0xa3, 0xb9, 0xf8, 0x18, 0xb3, 0xd7, 0x96,
	0x7d, 0x39, 0x16, 0xf6, 0x5d, 0xcc, 0x9d, 0x66, 0x24, 0xff, 0x90, 0xe7, 0xd0, 0x0a, 0x28, 0x63,
	0x37, 0x77, 0x6e, 0x28, 0x5c, 0x34, 0x7b, 0x9b, 0x28, 0x1d, 0x20, 0xec, 0x64, 0x02, 0x72, 0x02,
	0xe6, 0x44, 0x38, 0x18, 0x0b, 0xbd, 0x21, 0xf4, 0x04, 0xf5, 0x57, 0x39, 0xe3, 0x14, 0x65, 0xf6,
	0x6b, 0xe8, 0x0c, 0x5c, 0x4e, 0x19, 0xaf, 0x14, 0x55, 0x2e, 0x42, 0xab, 0x7a, 0x7c, 0x02, 0x5b,
	0x97, 0xaa, 0x9f, 0x49, 0xc8, 0xff, 0xf0, 0xd6, 0x04, 0x36, 0xf1, 0x16, 0x53, 0x37, 0x8e, 0xc0,
	0xb8, 0x4f, 0xbb, 0x24, 0xc4, 0x66, 0x6f, 0x0b, 0xbf, 0xb7, 0xd8, 0x40, 0x47, 0x2a, 0x4a, 0xc6,
	0x35, 0x96, 0x1a, 0x67, 0x9f, 0x65, 0x89, 0x1c, 0xca, 0x66, 0x51, 0xc8, 0x28, 0x39, 0x84, 0x26,
	0xbe, 0x40, 0x4c, 0xd5, 0x2e, 0xa7, 0x72, 0x14, 0x6d, 0xbf, 0x80, 0x4e, 0xb9, 0x36, 0x8c, 0xd0,
	0x01, 0x63, 0x9c, 0x02, 0x58, 0x97, 0x3c, 0xd8, 0x37, 0xf0, 0x5f, 0x5e, 0x13, 0x2a, 0x9f, 0x41,
	0x0b, 0x83, 0x31, 0x4b, 0xdb, 0xd7, 0x6b, 0x92, 0x65, 0x7c, 0x1e, 0x35, 0x2d, 0x69, 0x45, 0x45,
	0xfd, 0xae, 0x65, 0x15, 0x5c, 0x27, 0x23, 0xee, 0xf3, 0x60, 0x71, 0x54, 0x0f, 0x60, 0x83, 0x21,
	0x27, 0x07, 0x4d, 0x8e, 0xeb, 0xba, 0x02, 0xd5, 0xa4, 0xa9, 0x61, 0xcc, 0x67, 0x05, 0x91, 0xbe,
	0x47, 0x9e, 0x80, 0x19, 0xb8, 0xe1, 0x24, 0x71, 0x27, 0x82, 0x6f, 0x09, 0x1e, 0x14, 0xd4, 0xf7,
	0xec, 0x53, 0xd8, 0xa9, 0x7c, 0x07, 0x2b, 0x34, 0xbb, 0x10, 0x5a, 0xab, 0x84, 0xb6, 0x47, 0xb0,
	0x57, 0xbd, 0x39, 0xf0, 0x59, 0x6e, 0xe7, 0x45, 0x66, 0x5c, 0xc6, 0xa3, 0x59, 0xdb, 0x65, 0xb3,
	0x14, 0xed, 0x2c, 0xe8, 0xed, 0x6f, 0x60, 0x2a, 0x8c, 0xd2, 0xb0, 0x6e, 0x12, 0x0b, 0x6b, 0x46,
	0x5f, 0xbe, 0x66, 0x56, 0x6a, 0xd6, 0xcc, 0x12, 0xeb, 0x7a, 0xbf, 0xf4, 0x6c, 0x13, 0x5c, 0xd3,
	0xf8, 0x8b, 0x3f, 0xa6, 0xe4, 0x34, 0xdf, 0xab, 0xff, 0x57, 0x1a, 0x2e, 0x3d, 0xeb, 0x6e, 0x57,
	0x61, 0x34, 0xe3, 0x0c, 0x5a, 0xea, 0x15, 0x91, 0x8a, 0x46, 0xf9, 0xdd, 0xdd, 0x59, 0xc0, 0x33,
	0x27, 0x37, 0xdf, 0x45, 0xbc, 0x30, 0xc4, 0x7f, 0x11, 0xe3, 0x1c, 0xda, 0xef, 0xe9, 0xd7, 0x7f,
	0x0a, 0xf1, 0x16, 0x36, 0x4a, 0xab, 0x84, 0xec, 0xaa, 0x65, 0x55, 0xb3, 0x60, 0x1e, 0x74, 0xe2,
	0x2a, 0xdb, 0xde, 0x62, 0xfa, 0x48, 0xb7, 0xac, 0x2b, 0xae, 0x9b, 0xee, 0x6e, 0x2d, 0x87, 0x81,
	0x3e, 0x2d, 0xbe, 0x2f, 0xf2, 0xb8, 0xfe, 0x65, 0x65, 0xb5, 0x1d, 0x3c, 0xc0, 0x17, 0x1f, 0xee,
	0x68, 0x55, 0x68, 0x5e, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x69, 0xc9, 0x77, 0xee, 0x77, 0x07,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EpisodeServiceClient is the client API for EpisodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EpisodeServiceClient interface {
	Episode(ctx context.Context, in *EpisodeRequest, opts ...grpc.CallOption) (*EpisodeResponse, error)
	Episodes(ctx context.Context, in *EpisodesRequest, opts ...grpc.CallOption) (*EpisodesResponse, error)
	HottestEpisodes(ctx context.Context, in *EpisodesRequest, opts ...grpc.CallOption) (*EpisodesResponse, error)
	NewestEpisodes(ctx context.Context, in *EpisodesRequest, opts ...grpc.CallOption) (*EpisodesResponse, error)
	LatestEpisode(ctx context.Context, in *LatestEpisodeRequest, opts ...grpc.CallOption) (*EpisodeResponse, error)
	EpisodeCount(ctx context.Context, in *EpisodeCountRequest, opts ...grpc.CallOption) (*EpisodeCountResponse, error)
	EpisodeSubtitles(ctx context.Context, in *EpisodeSubtitlesRequest, opts ...grpc.CallOption) (*EpisodeSubtitlesListResponse, error)
}

type episodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEpisodeServiceClient(cc *grpc.ClientConn) EpisodeServiceClient {
	return &episodeServiceClient{cc}
}

func (c *episodeServiceClient) Episode(ctx context.Context, in *EpisodeRequest, opts ...grpc.CallOption) (*EpisodeResponse, error) {
	out := new(EpisodeResponse)
	err := c.cc.Invoke(ctx, "/proto.EpisodeService/Episode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodeServiceClient) Episodes(ctx context.Context, in *EpisodesRequest, opts ...grpc.CallOption) (*EpisodesResponse, error) {
	out := new(EpisodesResponse)
	err := c.cc.Invoke(ctx, "/proto.EpisodeService/Episodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodeServiceClient) HottestEpisodes(ctx context.Context, in *EpisodesRequest, opts ...grpc.CallOption) (*EpisodesResponse, error) {
	out := new(EpisodesResponse)
	err := c.cc.Invoke(ctx, "/proto.EpisodeService/HottestEpisodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodeServiceClient) NewestEpisodes(ctx context.Context, in *EpisodesRequest, opts ...grpc.CallOption) (*EpisodesResponse, error) {
	out := new(EpisodesResponse)
	err := c.cc.Invoke(ctx, "/proto.EpisodeService/NewestEpisodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodeServiceClient) LatestEpisode(ctx context.Context, in *LatestEpisodeRequest, opts ...grpc.CallOption) (*EpisodeResponse, error) {
	out := new(EpisodeResponse)
	err := c.cc.Invoke(ctx, "/proto.EpisodeService/LatestEpisode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodeServiceClient) EpisodeCount(ctx context.Context, in *EpisodeCountRequest, opts ...grpc.CallOption) (*EpisodeCountResponse, error) {
	out := new(EpisodeCountResponse)
	err := c.cc.Invoke(ctx, "/proto.EpisodeService/EpisodeCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodeServiceClient) EpisodeSubtitles(ctx context.Context, in *EpisodeSubtitlesRequest, opts ...grpc.CallOption) (*EpisodeSubtitlesListResponse, error) {
	out := new(EpisodeSubtitlesListResponse)
	err := c.cc.Invoke(ctx, "/proto.EpisodeService/EpisodeSubtitles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EpisodeServiceServer is the server API for EpisodeService service.
type EpisodeServiceServer interface {
	Episode(context.Context, *EpisodeRequest) (*EpisodeResponse, error)
	Episodes(context.Context, *EpisodesRequest) (*EpisodesResponse, error)
	HottestEpisodes(context.Context, *EpisodesRequest) (*EpisodesResponse, error)
	NewestEpisodes(context.Context, *EpisodesRequest) (*EpisodesResponse, error)
	LatestEpisode(context.Context, *LatestEpisodeRequest) (*EpisodeResponse, error)
	EpisodeCount(context.Context, *EpisodeCountRequest) (*EpisodeCountResponse, error)
	EpisodeSubtitles(context.Context, *EpisodeSubtitlesRequest) (*EpisodeSubtitlesListResponse, error)
}

// UnimplementedEpisodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEpisodeServiceServer struct {
}

func (*UnimplementedEpisodeServiceServer) Episode(ctx context.Context, req *EpisodeRequest) (*EpisodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Episode not implemented")
}
func (*UnimplementedEpisodeServiceServer) Episodes(ctx context.Context, req *EpisodesRequest) (*EpisodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Episodes not implemented")
}
func (*UnimplementedEpisodeServiceServer) HottestEpisodes(ctx context.Context, req *EpisodesRequest) (*EpisodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HottestEpisodes not implemented")
}
func (*UnimplementedEpisodeServiceServer) NewestEpisodes(ctx context.Context, req *EpisodesRequest) (*EpisodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewestEpisodes not implemented")
}
func (*UnimplementedEpisodeServiceServer) LatestEpisode(ctx context.Context, req *LatestEpisodeRequest) (*EpisodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestEpisode not implemented")
}
func (*UnimplementedEpisodeServiceServer) EpisodeCount(ctx context.Context, req *EpisodeCountRequest) (*EpisodeCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpisodeCount not implemented")
}
func (*UnimplementedEpisodeServiceServer) EpisodeSubtitles(ctx context.Context, req *EpisodeSubtitlesRequest) (*EpisodeSubtitlesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpisodeSubtitles not implemented")
}

func RegisterEpisodeServiceServer(s *grpc.Server, srv EpisodeServiceServer) {
	s.RegisterService(&_EpisodeService_serviceDesc, srv)
}

func _EpisodeService_Episode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodeServiceServer).Episode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EpisodeService/Episode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodeServiceServer).Episode(ctx, req.(*EpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpisodeService_Episodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpisodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodeServiceServer).Episodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EpisodeService/Episodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodeServiceServer).Episodes(ctx, req.(*EpisodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpisodeService_HottestEpisodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpisodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodeServiceServer).HottestEpisodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EpisodeService/HottestEpisodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodeServiceServer).HottestEpisodes(ctx, req.(*EpisodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpisodeService_NewestEpisodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpisodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodeServiceServer).NewestEpisodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EpisodeService/NewestEpisodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodeServiceServer).NewestEpisodes(ctx, req.(*EpisodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpisodeService_LatestEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatestEpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodeServiceServer).LatestEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EpisodeService/LatestEpisode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodeServiceServer).LatestEpisode(ctx, req.(*LatestEpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpisodeService_EpisodeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpisodeCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodeServiceServer).EpisodeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EpisodeService/EpisodeCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodeServiceServer).EpisodeCount(ctx, req.(*EpisodeCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpisodeService_EpisodeSubtitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpisodeSubtitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodeServiceServer).EpisodeSubtitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EpisodeService/EpisodeSubtitles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodeServiceServer).EpisodeSubtitles(ctx, req.(*EpisodeSubtitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EpisodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EpisodeService",
	HandlerType: (*EpisodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Episode",
			Handler:    _EpisodeService_Episode_Handler,
		},
		{
			MethodName: "Episodes",
			Handler:    _EpisodeService_Episodes_Handler,
		},
		{
			MethodName: "HottestEpisodes",
			Handler:    _EpisodeService_HottestEpisodes_Handler,
		},
		{
			MethodName: "NewestEpisodes",
			Handler:    _EpisodeService_NewestEpisodes_Handler,
		},
		{
			MethodName: "LatestEpisode",
			Handler:    _EpisodeService_LatestEpisode_Handler,
		},
		{
			MethodName: "EpisodeCount",
			Handler:    _EpisodeService_EpisodeCount_Handler,
		},
		{
			MethodName: "EpisodeSubtitles",
			Handler:    _EpisodeService_EpisodeSubtitles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/episode.proto",
}
