// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/genre.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Genre struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Thumbnail            string   `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Genre) Reset()         { *m = Genre{} }
func (m *Genre) String() string { return proto.CompactTextString(m) }
func (*Genre) ProtoMessage()    {}
func (*Genre) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c62409d78899ec0, []int{0}
}

func (m *Genre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Genre.Unmarshal(m, b)
}
func (m *Genre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Genre.Marshal(b, m, deterministic)
}
func (m *Genre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Genre.Merge(m, src)
}
func (m *Genre) XXX_Size() int {
	return xxx_messageInfo_Genre.Size(m)
}
func (m *Genre) XXX_DiscardUnknown() {
	xxx_messageInfo_Genre.DiscardUnknown(m)
}

var xxx_messageInfo_Genre proto.InternalMessageInfo

func (m *Genre) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Genre) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Genre) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

type GenreQuery struct {
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Pagination
	Offset               int64    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenreQuery) Reset()         { *m = GenreQuery{} }
func (m *GenreQuery) String() string { return proto.CompactTextString(m) }
func (*GenreQuery) ProtoMessage()    {}
func (*GenreQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c62409d78899ec0, []int{1}
}

func (m *GenreQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenreQuery.Unmarshal(m, b)
}
func (m *GenreQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenreQuery.Marshal(b, m, deterministic)
}
func (m *GenreQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenreQuery.Merge(m, src)
}
func (m *GenreQuery) XXX_Size() int {
	return xxx_messageInfo_GenreQuery.Size(m)
}
func (m *GenreQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GenreQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GenreQuery proto.InternalMessageInfo

func (m *GenreQuery) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GenreQuery) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GenreQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GenreRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenreRequest) Reset()         { *m = GenreRequest{} }
func (m *GenreRequest) String() string { return proto.CompactTextString(m) }
func (*GenreRequest) ProtoMessage()    {}
func (*GenreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c62409d78899ec0, []int{2}
}

func (m *GenreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenreRequest.Unmarshal(m, b)
}
func (m *GenreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenreRequest.Marshal(b, m, deterministic)
}
func (m *GenreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenreRequest.Merge(m, src)
}
func (m *GenreRequest) XXX_Size() int {
	return xxx_messageInfo_GenreRequest.Size(m)
}
func (m *GenreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenreRequest proto.InternalMessageInfo

func (m *GenreRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GenresRequest struct {
	Query                *GenreQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenresRequest) Reset()         { *m = GenresRequest{} }
func (m *GenresRequest) String() string { return proto.CompactTextString(m) }
func (*GenresRequest) ProtoMessage()    {}
func (*GenresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c62409d78899ec0, []int{3}
}

func (m *GenresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenresRequest.Unmarshal(m, b)
}
func (m *GenresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenresRequest.Marshal(b, m, deterministic)
}
func (m *GenresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenresRequest.Merge(m, src)
}
func (m *GenresRequest) XXX_Size() int {
	return xxx_messageInfo_GenresRequest.Size(m)
}
func (m *GenresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenresRequest proto.InternalMessageInfo

func (m *GenresRequest) GetQuery() *GenreQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

type GenreResponse struct {
	Genre                *Genre   `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenreResponse) Reset()         { *m = GenreResponse{} }
func (m *GenreResponse) String() string { return proto.CompactTextString(m) }
func (*GenreResponse) ProtoMessage()    {}
func (*GenreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c62409d78899ec0, []int{4}
}

func (m *GenreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenreResponse.Unmarshal(m, b)
}
func (m *GenreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenreResponse.Marshal(b, m, deterministic)
}
func (m *GenreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenreResponse.Merge(m, src)
}
func (m *GenreResponse) XXX_Size() int {
	return xxx_messageInfo_GenreResponse.Size(m)
}
func (m *GenreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenreResponse proto.InternalMessageInfo

func (m *GenreResponse) GetGenre() *Genre {
	if m != nil {
		return m.Genre
	}
	return nil
}

type GenresResponse struct {
	Genres               []*Genre `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenresResponse) Reset()         { *m = GenresResponse{} }
func (m *GenresResponse) String() string { return proto.CompactTextString(m) }
func (*GenresResponse) ProtoMessage()    {}
func (*GenresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c62409d78899ec0, []int{5}
}

func (m *GenresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenresResponse.Unmarshal(m, b)
}
func (m *GenresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenresResponse.Marshal(b, m, deterministic)
}
func (m *GenresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenresResponse.Merge(m, src)
}
func (m *GenresResponse) XXX_Size() int {
	return xxx_messageInfo_GenresResponse.Size(m)
}
func (m *GenresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenresResponse proto.InternalMessageInfo

func (m *GenresResponse) GetGenres() []*Genre {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *GenresResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Genre)(nil), "proto.Genre")
	proto.RegisterType((*GenreQuery)(nil), "proto.GenreQuery")
	proto.RegisterType((*GenreRequest)(nil), "proto.GenreRequest")
	proto.RegisterType((*GenresRequest)(nil), "proto.GenresRequest")
	proto.RegisterType((*GenreResponse)(nil), "proto.GenreResponse")
	proto.RegisterType((*GenresResponse)(nil), "proto.GenresResponse")
}

func init() { proto.RegisterFile("proto/genre.proto", fileDescriptor_0c62409d78899ec0) }

var fileDescriptor_0c62409d78899ec0 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x51, 0x4b, 0xf3, 0x40,
	0x10, 0x24, 0x49, 0x2f, 0xd0, 0xfd, 0xfa, 0x15, 0x7a, 0x56, 0x39, 0x8a, 0x48, 0x38, 0x04, 0xfb,
	0x54, 0x21, 0x45, 0xf0, 0x1f, 0xf4, 0x41, 0x1f, 0xf4, 0xfc, 0x05, 0xb6, 0xdd, 0xea, 0x41, 0x9a,
	0x6b, 0x73, 0x17, 0xa1, 0xff, 0x5e, 0xb2, 0x77, 0x21, 0x69, 0x7d, 0x4a, 0x76, 0x66, 0x67, 0x66,
	0x77, 0x0f, 0x26, 0x87, 0xca, 0x38, 0xf3, 0xf8, 0x85, 0x65, 0x85, 0x0b, 0xfa, 0xe7, 0x8c, 0x3e,
	0xf2, 0x05, 0xd8, 0xaa, 0x41, 0xf9, 0x18, 0x62, 0xbd, 0x15, 0x51, 0x16, 0xcd, 0x13, 0x15, 0xeb,
	0x2d, 0x9f, 0x02, 0x73, 0xda, 0x15, 0x28, 0xe2, 0x2c, 0x9a, 0x0f, 0x95, 0x2f, 0xf8, 0x2d, 0x0c,
	0xdd, 0x77, 0xbd, 0x5f, 0x97, 0x9f, 0xba, 0x10, 0x09, 0x31, 0x1d, 0x20, 0xdf, 0x00, 0xc8, 0xec,
	0xbd, 0xc6, 0xea, 0xd4, 0x39, 0x44, 0x7d, 0x87, 0x1b, 0x48, 0xcd, 0x6e, 0x67, 0xd1, 0x89, 0x01,
	0x65, 0x85, 0xaa, 0xe9, 0x2e, 0xf4, 0x5e, 0x3b, 0xc1, 0x08, 0xf6, 0x85, 0xbc, 0x83, 0x11, 0x39,
	0x2a, 0x3c, 0xd6, 0x68, 0xdd, 0xe5, 0x94, 0xf2, 0x19, 0xfe, 0x13, 0x6f, 0xdb, 0x86, 0x07, 0x60,
	0xc7, 0x26, 0x9d, 0x7a, 0xfe, 0xe5, 0x13, 0xbf, 0xed, 0xa2, 0x1b, 0x4b, 0x79, 0x5e, 0x2e, 0x83,
	0x52, 0xa1, 0x3d, 0x98, 0xd2, 0x22, 0x97, 0xc0, 0xe8, 0x3e, 0x41, 0x39, 0xea, 0x2b, 0x95, 0xa7,
	0xe4, 0x2b, 0x8c, 0xdb, 0xb8, 0xa0, 0xba, 0x87, 0x94, 0x28, 0x2b, 0xa2, 0x2c, 0xf9, 0x23, 0x0b,
	0x5c, 0xb3, 0xdc, 0xc6, 0xd4, 0xa5, 0xa3, 0x63, 0x0e, 0x94, 0x2f, 0xf2, 0x53, 0x58, 0xee, 0x03,
	0xab, 0x1f, 0xbd, 0x41, 0x9e, 0xb7, 0x6f, 0x71, 0x75, 0x66, 0xe2, 0x37, 0x9b, 0x4d, 0xcf, 0xc1,
	0x90, 0xff, 0x04, 0xe9, 0x2a, 0x64, 0xf4, 0xf9, 0xf6, 0x1e, 0xb3, 0xeb, 0x0b, 0xd4, 0xcb, 0xd6,
	0x29, 0xa1, 0xcb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xa0, 0x07, 0x7a, 0x19, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GenreServiceClient is the client API for GenreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GenreServiceClient interface {
	Genre(ctx context.Context, in *GenreRequest, opts ...grpc.CallOption) (*GenreResponse, error)
	Genres(ctx context.Context, in *GenresRequest, opts ...grpc.CallOption) (*GenresResponse, error)
}

type genreServiceClient struct {
	cc *grpc.ClientConn
}

func NewGenreServiceClient(cc *grpc.ClientConn) GenreServiceClient {
	return &genreServiceClient{cc}
}

func (c *genreServiceClient) Genre(ctx context.Context, in *GenreRequest, opts ...grpc.CallOption) (*GenreResponse, error) {
	out := new(GenreResponse)
	err := c.cc.Invoke(ctx, "/proto.GenreService/Genre", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genreServiceClient) Genres(ctx context.Context, in *GenresRequest, opts ...grpc.CallOption) (*GenresResponse, error) {
	out := new(GenresResponse)
	err := c.cc.Invoke(ctx, "/proto.GenreService/Genres", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenreServiceServer is the server API for GenreService service.
type GenreServiceServer interface {
	Genre(context.Context, *GenreRequest) (*GenreResponse, error)
	Genres(context.Context, *GenresRequest) (*GenresResponse, error)
}

// UnimplementedGenreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGenreServiceServer struct {
}

func (*UnimplementedGenreServiceServer) Genre(ctx context.Context, req *GenreRequest) (*GenreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Genre not implemented")
}
func (*UnimplementedGenreServiceServer) Genres(ctx context.Context, req *GenresRequest) (*GenresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Genres not implemented")
}

func RegisterGenreServiceServer(s *grpc.Server, srv GenreServiceServer) {
	s.RegisterService(&_GenreService_serviceDesc, srv)
}

func _GenreService_Genre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenreServiceServer).Genre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GenreService/Genre",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenreServiceServer).Genre(ctx, req.(*GenreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenreService_Genres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenreServiceServer).Genres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GenreService/Genres",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenreServiceServer).Genres(ctx, req.(*GenresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GenreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GenreService",
	HandlerType: (*GenreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Genre",
			Handler:    _GenreService_Genre_Handler,
		},
		{
			MethodName: "Genres",
			Handler:    _GenreService_Genres_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/genre.proto",
}
